FROM 	ubuntu:24.04

LABEL 	org.label-schema.architecture=amd64
LABEL 	org.label-schema.changelog-url=https://github.com/LearningToPi/mrtg/blob/main/release_notes/v3.0.0.md
LABEL 	org.label-schema.description="Lightweight image to run MRTG to generate the image data. Map the /var/www/mrtg to an appropriate web server (none included)"
LABEL 	org.label-schema.name=mrtg
LABEL 	org.label-schema.release=ubuntu24.04-3.0.0
LABEL 	org.label-schema.schema-version=1.0
LABEL 	org.label-schema.url=https://www.learningtopi.com/python-modules-applications/azure_smtp_relay/
LABEL 	org.label-schema.usage=README.md
LABEL 	org.label-schema.vcs-url=https://github.com/LearningToPi/mrtg/tree/v3.0.0
LABEL 	org.label-schema.vendor=LearningToPi.com
LABEL 	org.label-schema.version=3.0.1
LABEL 	org.opencontainers.image.ref.name=ubuntu
LABEL 	org.opencontainers.image.version=24.04

RUN 	apt-get update && apt-get -y upgrade && apt-get -y install snmp snmp-mibs-downloader mrtg cron mrtg-ping-probe iputils-ping dnsutils lighttpd
RUN	echo '*/5 * * * * mrtg bash -c "source /tmp/env && /usr/bin/mrtg /etc/mrtg/mrtg.cfg 2>&1"' > /etc/cron.d/mrtg

ADD	lighttpd.conf /etc/lighttpd/lighttpd.conf
ADD 	entrypoint.sh /entrypoint.sh
ADD	healthcheck.sh /healthcheck.sh

HEALTHCHECK	--interval=5m --timeout=60s --retries=3 CMD /healthcheck.sh

ENTRYPOINT	["/entrypoint.sh"]
